name = "WidthLimitedIO"
uuid = "b8c1c048-cf81-46c6-9da0-18c1d99e41f2"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
